services:
  frontend:
    image: nepudev/gb-maderas-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app

  backend:
    image: nepudev/gb-maderas-backend:latest
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_URL=http://138.197.17.116
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=maderas_ubb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=maderas_ubb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app

volumes:
  dbdata: {}

networks:
  app:
    driver: bridge
